import type { AjoGroup, Organization } from "./types.t";

const mockOrgs: Organization[] = [
  {
    id: "1",
    name: "Lagos Food Bank",
    type: "NGO",
    impactScore: 92,
    totalDonations: 45000000,
    activeProjects: 12,
    transparency: "High",
  },
  {
    id: "2",
    name: "Abuja Children Foundation",
    type: "Charity",
    impactScore: 78,
    totalDonations: 23000000,
    activeProjects: 8,
    transparency: "Medium",
  },
  {
    id: "3",
    name: "Victory Church Lagos",
    type: "Religious",
    impactScore: 45,
    totalDonations: 120000000,
    activeProjects: 3,
    transparency: "Low",
  },
  {
    id: "4",
    name: "Rivers State Youth Initiative",
    type: "NGO",
    impactScore: 88,
    totalDonations: 32000000,
    activeProjects: 15,
    transparency: "High",
  },
];

export const ajoGroups: AjoGroup[] = [
  {
    id: "1",
    name: "Tech Bros Ajo",
    description:
      "For software developers and tech entrepreneurs building wealth together",
    monthlyPayment: 50000,
    totalMembers: 12,
    currentMembers: 8,
    paymentToken: "USDC",
    cycleLength: 30,
    collateralRequired: 27500,
    nextPayout: "5 days",
    status: "active",
    creator: "Chidi O.",
    reputation: 98,
    totalSaved: 2400000,
    completedCycles: 3,
  },
  {
    id: "2",
    name: "Lagos Landlords Circle",
    description:
      "Property investors and real estate professionals saving for bigger deals",
    monthlyPayment: 100000,
    totalMembers: 8,
    currentMembers: 6,
    paymentToken: "USDC",
    cycleLength: 30,
    collateralRequired: 55000,
    nextPayout: "12 days",
    status: "forming",
    creator: "Kemi A.",
    reputation: 95,
    totalSaved: 4800000,
    completedCycles: 2,
  },
  {
    id: "3",
    name: "Startup Founders Fund",
    description:
      "Early-stage entrepreneurs pooling resources for business growth",
    monthlyPayment: 75000,
    totalMembers: 15,
    currentMembers: 15,
    paymentToken: "HBAR",
    cycleLength: 30,
    collateralRequired: 41250,
    nextPayout: "20 days",
    status: "active",
    creator: "Aisha M.",
    reputation: 99,
    totalSaved: 6750000,
    completedCycles: 5,
  },
  {
    id: "4",
    name: "Abuja Young Professionals",
    description:
      "Government workers and private sector professionals building financial security",
    monthlyPayment: 30000,
    totalMembers: 20,
    currentMembers: 12,
    paymentToken: "USDC",
    cycleLength: 30,
    collateralRequired: 16500,
    nextPayout: "Forming",
    status: "forming",
    creator: "Emeka N.",
    reputation: 92,
    totalSaved: 1800000,
    completedCycles: 1,
  },
  {
    id: "5",
    name: "Market Traders Alliance",
    description:
      "Small business owners and traders from major Nigerian markets",
    monthlyPayment: 25000,
    totalMembers: 25,
    currentMembers: 25,
    paymentToken: "HBAR",
    cycleLength: 30,
    collateralRequired: 13750,
    nextPayout: "8 days",
    status: "active",
    creator: "Fatima B.",
    reputation: 96,
    totalSaved: 3750000,
    completedCycles: 4,
  },
  {
    id: "6",
    name: "University Alumni Network",
    description:
      "Graduates from top Nigerian universities supporting each other",
    monthlyPayment: 40000,
    totalMembers: 18,
    currentMembers: 14,
    paymentToken: "USDC",
    cycleLength: 30,
    collateralRequired: 22000,
    nextPayout: "Forming",
    status: "forming",
    creator: "Tunde L.",
    reputation: 94,
    totalSaved: 2160000,
    completedCycles: 2,
  },
];
